version: '3.8'

services:
  go:
    build:
      context: .
    container_name: go
    ports:
      - "8080:8080"
    depends_on:
      - "db"

  db:
    image: mysql:8.0.32
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: testdb
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  my-db:
